apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsdeployment
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nodejsapp
  template:
    metadata:
      name: nodejspod
      labels:
        app: nodejsapp
    spec:
      containers:
      - name: nodejscontainer
        image: docker13143/node-js-app:VERSION
        ports:
        - containerPort: 9981
---
apiVersion: v1
kind: Service
metadata:
  name: nodejssvc
spec:
  type: NodePort
  selector:
    app: nodejsapp
  ports:
  - port: 80
    targetPort: 9981
